https://habr.com/ru/post/150732/
MCPN/AVL pull request #1
Opened 2019-06-10 19:59 UTC by MCPN

2019-06-16 20:44 UTC, glebshp commented on avl_tree.cpp
> +        } else {
Что происходит в этом else, нужно пояснение

2019-06-16 20:45 UTC, glebshp commented on avl_tree.cpp
> +    // Functions that used in deletion in order to swap min and elem
Этот комментарий:
1. Непонятен
2. Неграмотен

2019-06-16 20:46 UTC, glebshp commented on avl_tree.cpp
> +    Node* balance(Node *node) {
Комментарии в этом методе достаточно бесполезные, они поясняют действия, которые и так следуют из названия функций, и не поясняют нетривиальные. Что значит баланс 2? Что значит баланс -2?

2019-06-16 20:49 UTC, glebshp commented on avl_tree.cpp
> +    Set(const Set &other): Set() {
В данном случае принято писать const Set& other, аналогично почти во всём остальном коде. Аналогично со *

2019-06-16 20:50 UTC, glebshp requested changes
Улучшить комментарии, сделать указание типов int *a -> int* a и int &a -> int& a

2019-06-16 20:51 UTC, MCPN commented
Произошел маркдаун (int a -> int a, звездочки заменились на курсив)

2019-06-24 23:51 UTC, glebshp approved these changes

2019-06-25 07:08 UTC, merged